### ISSUE TITLE
Uninstall doesn't delete AppData\Local\Unicodex?

### ISSUE THREAD

**Issue by jamesluke** [garcia/unicodex#1]
I managed to hose my install of Unicodex by setting some configuration option incorrectly, causing the application to crash shortly after the tray icon appeared. (The offending setting may have been enabling "spawn relative to active monitor" with mirrored monitors, though that is at best a shot in the dark). I gave up and tried uninstalling and reinstalling, but the old config wasn't cleared. It seems that AppData\Local\Unicodex isn't deleted during the uninstall.

Is this expected behavior? I know Windows has some "quirks" [speaking charitably] around file and folder deletion, so it's possible the files were marked for deletion at next reboot. All the same, it probably makes sense to check for an old config file during installation and overwrite it with the default.

**Comment by garcia** [comment]
Thanks for the report. I wasn't able to reproduce the crash as described; I'd be interested to see your user.config, or at least the `<Preferences ...>` block.

The Wix uninstaller *should* take care of everything by default, barring GUID refcount issues (have you installed the app multiple times?). I'll have to do some testing on a separate machine to see what's going on.

**Comment by jamesluke** [comment]
Sorry for the delay in responding! Can't seem to reproduce my own bug report. :/
Apologies for the spurious report, I hope it didn't take up too much of your time.

Closing this.

**Comment by garcia** [comment]
No worries. The installer is something I need to look at more closely when I have the time to finish this project up. Hopefully it'll be more foolproof whenever 1.0 comes out.
